### ISSUE TITLE
Fluid

### ISSUE THREAD

**Issue by MelanX** [noeppi-noeppi/MappingUtilities#4]
**Name requests**

Mappings:
func_215664_b,getShape,2,Gets the shape of the fluid
p_215664_1_,fluidState,2,
p_215664_2_,blockReader,2,
p_215664_3_,pos,2,
p_205569_1_,world,2,
p_215662_1_,state,2,
p_215662_2_,world,2,
p_215662_3_,pos,2,
p_223407_1_,state,2,

This issue is intended as a contribution to the MCP unofficial project. I acknowledge that the LICENSE and CONTRIBUTING documents in `mcp_unofficial` apply.

Here is a copy of the CONTRIBUTING file. This is intended to make things more clear. In case that this differs to the contents of the CONTRIBUTING file in `mcp_unofficial` at the time this issue was created, the contents from the CONTRIBUTING in `mcp_unofficial` apply.

> I dedicate any and all copyright interest in this software to the
public domain. I make this dedication for the benefit of the public at
large and to the detriment of my heirs and successors. I intend this
dedication to be an overt act of relinquishment in perpetuity of all
present and future rights to this software under copyright law.
> 
> I confirm that I have neither used the official obfuscation maps provided
by Mojang, nor any other Mappings for the game MineCraft except mcpbot
exports, McpConfig (https://github.com/MinecraftForge/MCPConfig/) and
mappings published at https://github.com/noeppi-noeppi/MappingUtilities
anywhere in the process of naming things for MCP unofficial.

**Comment by noeppi-noeppi** [comment]
I don't want to archive this with an open issue
